// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S26W10CodeFirstApproach;

#nullable disable

namespace S26W10CodeFirstApproach.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("S26W10CodeFirstApproach.Standard", b =>
                {
                    b.Property<int>("StandardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StandardId"));

                    b.Property<string>("StandardName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StandardId");

                    b.ToTable("Standards");

                    b.HasData(
                        new
                        {
                            StandardId = 1,
                            StandardName = "Standard 1"
                        },
                        new
                        {
                            StandardId = 2,
                            StandardName = "Standard 2"
                        },
                        new
                        {
                            StandardId = 3,
                            StandardName = "Standard 3"
                        },
                        new
                        {
                            StandardId = 4,
                            StandardName = "Standard 4"
                        },
                        new
                        {
                            StandardId = 5,
                            StandardName = "Standard 5"
                        });
                });

            modelBuilder.Entity("S26W10CodeFirstApproach.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("StandardId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("StandardId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            StandardId = 1,
                            StudentName = "Ross"
                        },
                        new
                        {
                            StudentId = 2,
                            StandardId = 1,
                            StudentName = "Rachel"
                        },
                        new
                        {
                            StudentId = 3,
                            StandardId = 2,
                            StudentName = "Chandler"
                        },
                        new
                        {
                            StudentId = 4,
                            StandardId = 2,
                            StudentName = "Monica"
                        },
                        new
                        {
                            StudentId = 5,
                            StandardId = 3,
                            StudentName = "Joey"
                        },
                        new
                        {
                            StudentId = 6,
                            StandardId = 4,
                            StudentName = "Phoebe"
                        });
                });

            modelBuilder.Entity("S26W10CodeFirstApproach.Student", b =>
                {
                    b.HasOne("S26W10CodeFirstApproach.Standard", "Standard")
                        .WithMany("Students")
                        .HasForeignKey("StandardId");

                    b.Navigation("Standard");
                });

            modelBuilder.Entity("S26W10CodeFirstApproach.Standard", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
